[toolchain]
anchor_version = "0.30.1"

[features]
resolution = false
seeds = false
skip-lint = true
no-log-ix-name = true
no-idl = false
idl-build = true

[programs.localnet]
moon_wallet_program = "5tFJskbgqrPxb992SUf6JzcQWJGbJuvsta2pRnZBcygN"

[programs.devnet]
moon_wallet_program = "5tFJskbgqrPxb992SUf6JzcQWJGbJuvsta2pRnZBcygN"

[programs.mainnet]
moon_wallet_program = "5tFJskbgqrPxb992SUf6JzcQWJGbJuvsta2pRnZBcygN"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/tai/.config/solana/id.json"
commitment = "processed"
pre_flight = false
timeout = 300000  # 5 phút để chờ giao dịch triển khai

[dependencies] 
bytemuck_derive = "=1.7.0"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[workspace]
types = "./types"

[test]
startup_wait = 10000




