[toolchain]
anchor_version = "0.31.1"

[features]
resolution = false
seeds = false
skip-lint = true
no-log-ix-name = true
no-idl = false
idl-build = true

[programs.localnet]
moon_wallet_program = "6Y3N5AQRQtviTrmRcf29yHWBu3ft7xEoj8kqmykDGvKP"

[programs.devnet]
moon_wallet_program = "6Y3N5AQRQtviTrmRcf29yHWBu3ft7xEoj8kqmykDGvKP"

[programs.mainnet]
moon_wallet_program = "6Y3N5AQRQtviTrmRcf29yHWBu3ft7xEoj8kqmykDGvKP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://ready-wasp-saving.ngrok-free.app"
wallet = "/Users/tai/.config/solana/id.json"
commitment = "confirmed"
pre_flight = false
timeout = 60000  # 10 phút để chờ giao dịch triển khai
ws_url = "wss://54e8-42-116-188-40.ngrok-free.app/ws"


[dependencies] 
bytemuck_derive = "=1.7.0"
proc-macro2 = { version = "1.0.95" }

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[workspace]
types = "./types"

[test]
startup_wait = 10000




