[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false
seeds = false

[programs.localnet]
moon_wallet_program = "8z1cp83P8qTvmQzrF6PJfjq565MnKcpKkk2EUe4g574C"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"